parameters:

services:
###################################################################
## Services you should override/extend in your bundle
###################################################################
    azine_email.example.template_provider:
        class: Azine\EmailBundle\Services\AzineTemplateProvider
        arguments:
          router:       "@router"
          translator:   "@translator.default"
          parameters:
            image_dir:  "%azine_email_image_dir%"
            allowed_images_folders: "%azine_email_allowed_images_folders%"
            campaign_param_name: "%azine_email_campaign_param_name%"
            campaign_keyword_param_name: "%azine_email_campaign_keyword_param_name%"

    azine_email.example.notifier_service:
        class: Azine\EmailBundle\Services\AzineNotifierService
        arguments:
          mailer:             "@azine_email_template_twig_swift_mailer"
          twig:               "@twig"
          logger:             "@logger"
          router:             "@router"
          entityManager:      "@doctrine.orm.entity_manager"
          templateProvider:   "@azine_email_template_provider"
          recipientProvider:  "@azine_email_recipient_provider"
          translatorService:  "@translator.default"
          parameters:
            newsletter_interval : "%azine_email_newsletter_interval%"
            newsletter_send_time: "%azine_email_newsletter_send_time%"
            templates_newsletter:     "%azine_email_templates_newsletter%"
            templates_notifications:  "%azine_email_templates_notifications%"
            templates_content_item:   "%azine_email_templates_content_item%"

    azine_email.example.web_view_service:
        class: Azine\EmailBundle\Services\AzineWebViewService
        arguments:
          router:       "@router"


###################################################################
## Services you can use as default if you work with the FOSUserBundle
###################################################################
    azine_email.default.template_twig_swift_mailer:
        class: Azine\EmailBundle\Services\AzineTwigSwiftMailer
        arguments:
          mailer:             "@mailer"
          router:             "@router"
          twig:               "@twig"
          logger:             "@logger"
          translator:         "@translator.default"
          templateProvider:   "@azine_email_template_provider"
          entityManager:      "@doctrine.orm.entity_manager"
          parameters:
            template:
              confirmation :  "%fos_user.registration.confirmation.template%"
              resetting:      "%fos_user.resetting.email.template%"
            from_email:
              confirmation:   "%fos_user.registration.confirmation.from_email%"
              resetting:      "%fos_user.resetting.email.from_email%"
            no_reply:         "%azine_email_no_reply%"
          immediateMailer:    "@swiftmailer.mailer.immediateMailer"

    azine_email.default.recipient_provider:
        class: Azine\EmailBundle\Services\AzineRecipientProvider
        arguments:
          entityManager:      "@doctrine.orm.entity_manager"
          recipient_class:   "%azine_email_recipient_class%"
          newsletterField:    "%azine_email_recipient_newsletter_field%"

###################################################################
## Twig-Filter
###################################################################
    azine.email.bundle.twig.filters:
        class: Azine\EmailBundle\Services\AzineEmailTwigExtension
        public: false
        tags:
            - { name: twig.extension }
